/* Derived from Numbas (https://github.com/numbas/Numbas), Copyright 2011-2026 Newcastle University.
 * Licensed under the Apache License, Version 2.0. Ported to TypeScript for SAVINT; see packages/engine/NOTICE. */

// Porting di runtime/scripts/unicode-mappings.js: dato puro, consumato solo dal
// tokenizer (`ops`, `re_name`, `re_subscript_character`, `re_math_letter`,
// `normaliseName`, `normalisePunctuation`, `normaliseOp`) e da `re_greek` in
// tokens.ts. Le tabelle sono convertite meccanicamente dal file upstream
// mantenendo l'ordine delle chiavi. `letters` (1124 voci) sta in
// unicode-letters.ts e viene ri-esportata qui.

/** Una sostituzione Unicode: il testo di rimpiazzo e le annotazioni di stile
 * (es. `["A", ["BOLD"]]` per 𝐀). */
export type UnicodeReplacement = [replacement: string, annotations: string[]];

export { letters } from "./unicode-letters";

/** Lettere greche → il loro nome ASCII. */
export const greek: Record<string, string> = {
  "Α": "Alpha",
  "Β": "Beta",
  "Χ": "Chi",
  "Δ": "Delta",
  "Ε": "Epsilon",
  "Η": "Eta",
  "Γ": "Gamma",
  "Ͱ": "Heta",
  "Ι": "Iota",
  "Κ": "Kappa",
  "Λ": "Lambda",
  "Μ": "Mu",
  "Ν": "Nu",
  "Ω": "Omega",
  "Ο": "Omicron",
  "Φ": "Phi",
  "Π": "Pi",
  "Ψ": "Psi",
  "Ρ": "Rho",
  "Ϻ": "San",
  "Ϸ": "Sho",
  "Σ": "Sigma",
  "Τ": "Tau",
  "Θ": "Theta",
  "Υ": "Upsilon",
  "Ξ": "Xi",
  "Ϳ": "Yot",
  "Ζ": "Zeta",
  "ᴦ": "Gamma",
  "ᴧ": "Lambda",
  "ꭥ": "Omega",
  "ᴨ": "Pi",
  "ᴪ": "Psi",
  "ᴩ": "Rho",
  "α": "alpha",
  "β": "beta",
  "χ": "chi",
  "δ": "delta",
  "ϝ": "digamma",
  "ε": "epsilon",
  "η": "eta",
  "ς": "sigma",
  "γ": "gamma",
  "ͱ": "heta",
  "ι": "iota",
  "κ": "kappa",
  "ϟ": "koppa",
  "λ": "lambda",
  "μ": "mu",
  "ν": "nu",
  "ω": "omega",
  "ο": "omicron",
  "φ": "phi",
  "π": "pi",
  "ψ": "psi",
  "ρ": "rho",
  "ϡ": "sampi",
  "ϻ": "san",
  "ϸ": "sho",
  "σ": "sigma",
  "ϛ": "stigma",
  "τ": "tau",
  "θ": "theta",
  "υ": "upsilon",
  "ξ": "xi",
  "ζ": "zeta",
};

/** Caratteri in pedice → il carattere normale corrispondente. */
export const subscripts: Record<string, string> = {
  "ᵢ": "i",
  "ᵣ": "r",
  "ᵤ": "u",
  "ᵥ": "v",
  "ᵦ": "β",
  "ᵧ": "γ",
  "ᵨ": "ρ",
  "ᵩ": "φ",
  "ᵪ": "χ",
  "₀": "0",
  "₁": "1",
  "₂": "2",
  "₃": "3",
  "₄": "4",
  "₅": "5",
  "₆": "6",
  "₇": "7",
  "₈": "8",
  "₉": "9",
  "₊": "+",
  "₋": "-",
  "₌": "=",
  "₍": "(",
  "₎": ")",
  "ₐ": "a",
  "ₑ": "e",
  "ₒ": "o",
  "ₓ": "x",
  "ₕ": "h",
  "ₖ": "k",
  "ₗ": "l",
  "ₘ": "m",
  "ₙ": "n",
  "ₚ": "p",
  "ₛ": "s",
  "ₜ": "t",
  "ⱼ": "j",
};

/** Caratteri in apice → il carattere normale corrispondente. */
export const superscripts: Record<string, string> = {
  "²": "2",
  "³": "3",
  "¹": "1",
  "⁰": "0",
  "ⁱ": "i",
  "⁴": "4",
  "⁵": "5",
  "⁶": "6",
  "⁷": "7",
  "⁸": "8",
  "⁹": "9",
  "⁺": "+",
  "⁻": "-",
  "⁼": "=",
  "⁽": "(",
  "⁾": ")",
  "ⁿ": "n",
};

/** Simboli di operatore Unicode → nome dell'operatore JME. */
export const symbols: Record<string, UnicodeReplacement> = {
  "~": ["~", []],
  "¬": ["not", []],
  "×": ["*", []],
  "÷": ["/", []],
  "∈": ["in", []],
  "∓": ["pm", []],
  "∧": ["and", []],
  "∨": ["or", []],
  "±": ["pm", []],
  "؆": ["cube_root", []],
  "؇": ["fourth_root", []],
  "⁄": ["/", []],
  "⁒": ["-", []],
  "₋": ["-", []],
  "℘": ["P", ["SCRIPT"]],
  "⅀": ["sum", ["DOUBLE-STRUCK"]],
  "∀": ["forall", []],
  "∁": ["complement", []],
  "∂": ["pdiff", []],
  "∃": ["exists", []],
  "∄": ["not exists", []],
  "∆": ["increment", []],
  "∇": ["nabla", []],
  "∉": ["not in", []],
  "∊": ["in", []],
  "∋": ["contains", []],
  "∌": ["not contains", []],
  "∍": ["contains", []],
  "∏": ["product", []],
  "∐": ["coproduct", []],
  "∑": ["sum", []],
  "−": ["-", []],
  "∔": ["+", ["DOT"]],
  "∕": ["/", []],
  "∖": ["setminus", []],
  "∗": ["*", []],
  "∘": ["circ", []],
  "∙": ["cdot", []],
  "√": ["sqrt", []],
  "∛": ["cube_root", []],
  "∜": ["fourth_root", []],
  "∝": ["propto", []],
  "∟": ["right_angle", []],
  "∠": ["angle", []],
  "∣": ["divides", []],
  "∤": ["not divides", []],
  "∥": ["parallel_to", []],
  "∦": ["not parallel_to", []],
  "∩": ["intersection", []],
  "∪": ["union", []],
  "∫": ["integral", []],
  "∮": ["contour_integral", []],
  "∯": ["surface_integral", []],
  "∰": ["volume_integral", []],
  "∱": ["clockwise_integral", []],
  "∲": ["clockwise_contour_integral", []],
  "∳": ["anticlockwise_contour_integral", []],
  "∴": ["therefore", []],
  "∵": ["because", []],
  "∶": [":", []],
  "∷": ["::", []],
  "∸": ["-", ["DOT"]],
  "∼": ["~", []],
  "∽": ["~", []],
  "≀": ["wreath", []],
  "≁": ["not ~", []],
  "≅": ["approx", []],
  "≠": ["<>", []],
  "≡": ["identical", []],
  "≢": ["not identical", []],
  "≺": ["prec", []],
  "≻": ["succ", []],
  "≼": ["prec_eq", []],
  "≽": ["succ_eq", []],
  "⊀": ["not prec", []],
  "⊁": ["not succ", []],
  "⊂": ["subset", []],
  "⊃": ["superset", []],
  "⊄": ["not subset", []],
  "⊅": ["not superset", []],
  "⊆": ["subset_eq", []],
  "⊇": ["superset_eq", []],
  "⊈": ["not subset_eq", []],
  "⊉": ["not superset_eq", []],
  "⊊": ["subset_neq", []],
  "⊋": ["superset_neq", []],
  "⊓": ["cap", ["SQUARE"]],
  "⊔": ["cup", ["SQUARE"]],
  "⊕": ["+", ["CIRCLE"]],
  "⊖": ["-", ["CIRCLE"]],
  "⊗": ["*", ["CIRCLE"]],
  "⊘": ["/", ["CIRCLE"]],
  "⊙": ["cdot", ["CIRCLE"]],
  "⊚": ["circ", ["CIRCLE"]],
  "⊛": ["*", ["CIRCLE"]],
  "⊜": ["=", ["CIRCLE"]],
  "⊝": ["-", ["CIRCLE"]],
  "⊞": ["+", ["SQUARE"]],
  "⊟": ["-", ["SQUARE"]],
  "⊠": ["*", ["SQUARE"]],
  "⊡": ["cdot", ["SQUARE"]],
  "⊰": ["prec", ["RELATION"]],
  "⊱": ["prec", ["RELATION"]],
  "⊲": ["normal_subgroup", []],
  "⊳": ["contains_normal_subgroup", []],
  "⊴": ["normal_subgroup_eq", []],
  "⊵": ["contains_normal_subgroup_eq", []],
  "⊻": ["xor", []],
  "⊼": ["nand", []],
  "⊽": ["nor", []],
  "⊾": ["right_angle ARC", []],
  "⊿": ["right_triangle", []],
  "⋀": ["and", []],
  "⋁": ["or", []],
  "⋂": ["intersection", []],
  "⋃": ["union", []],
  "⋄": ["diamond", []],
  "⋅": ["cdot", []],
  "⋆": ["star", []],
  "⋇": ["divide_times", []],
  "⋈": ["bowtie", []],
  "⋎": ["or", ["CURLY"]],
  "⋏": ["and", ["CURLY"]],
  "⋐": ["subset", ["DOUBLE"]],
  "⋑": ["superset", ["DOUBLE"]],
  "⋒": ["intersection", ["DOUBLE"]],
  "⋓": ["union", ["DOUBLE"]],
  "≤": ["<=", []],
  "≥": [">=", []],
  "⋖": ["<", ["DOT"]],
  "⋗": [">", ["DOT"]],
  "⋜": ["<=", []],
  "⋝": [">=", []],
  "⋞": ["prec_eq", []],
  "⋟": ["succ_eq", []],
  "⋠": ["not prec_eq", []],
  "⋡": ["not succ_eq", []],
  "⋪": ["not normal_subgroup", []],
  "⋫": ["not contains_normal_subgroup", []],
  "⋬": ["not normal_subgroup_eq", []],
  "⋭": ["not contains_normal_subgroup_eq", []],
  "⟀": ["angle", ["THREE-DIMENSIONAL"]],
  "⟂": ["perpendicular", []],
  "⟃": ["subset", ["OPEN"]],
  "⟄": ["superset", ["OPEN"]],
  "⟇": ["or", ["DOT"]],
  "⟌": ["/", []],
  "⟎": ["and", ["SQUARE"]],
  "⟏": ["or", ["SQUARE"]],
  "⟑": ["and", ["DOT"]],
  "⟒": ["in", ["UPWARDS"]],
  "⟹": ["implies", []],
  "⟺": ["iff", []],
  "⦜": ["right_angle", ["SQUARE"]],
  "⦝": ["right_angle", ["DOT"]],
  "⦞": ["angle", []],
  "⦟": ["angle", ["ACUTE"]],
  "⦶": ["|", ["CIRCLE"]],
  "⦷": ["parallel_to", ["CIRCLE"]],
  "⦸": ["/", ["CIRCLE", "REVERSE"]],
  "⦹": ["perpendicular", ["CIRCLE"]],
  "⧀": ["<", ["CIRCLE"]],
  "⧁": [">", ["CIRCLE"]],
  "⧆": ["*", ["SQUARE"]],
  "⧇": ["circ", ["SQUARE"]],
  "⧺": ["+", ["DOUBLE"]],
  "⧻": ["+", ["TRIPLE"]],
  "⨀": ["dot", ["CIRCLE"]],
  "⨁": ["+", ["CIRCLE"]],
  "⨂": ["*", ["CIRCLE"]],
  "⨅": ["intersection", []],
  "⨆": ["union", ["SQUARE"]],
  "⨇": ["and", ["DOUBLE"]],
  "⨈": ["or", ["DOUBLE"]],
  "⨉": ["*", []],
  "⨝": ["join", []],
  "⨯": ["cross", []],
  "⨳": ["smash", []],
  "⩑": ["and", ["DOT"]],
  "⩒": ["or", ["DOT"]],
  "⩓": ["and", ["DOUBLE"]],
  "⩔": ["or", ["DOUBLE"]],
  "⩗": ["or", ["SLOPING"]],
  "⩘": ["and", ["SLOPING"]],
  "⩦": ["=", ["DOT"]],
  "⩧": ["identical", ["DOT"]],
  "⩪": ["~", ["DOT"]],
  "⩭": ["congruent", ["DOT"]],
  "⪪": ["<", []],
  "⪫": [">", []],
  "⪬": ["<=", []],
  "⪭": [">=", []],
  "⪻": ["prec", ["DOUBLE"]],
  "⪼": ["succ", ["DOUBLE"]],
  "⪽": ["subset", ["DOT"]],
  "⪾": ["superset", ["DOT"]],
  "⫏": ["subset", ["CLOSED"]],
  "⫐": ["superset", ["CLOSED"]],
  "⫑": ["subset_eq", ["CLOSED"]],
  "⫒": ["superset_eq", ["CLOSED"]],
  "⫙": ["in", ["DOWNWARDS"]],
  "～": ["~", []],
  "𝛁": ["nabla", ["BOLD"]],
  "𝛛": ["pdiff", ["BOLD"]],
  "𝛻": ["nabla", ["ITALIC"]],
  "𝜕": ["pdiff", ["ITALIC"]],
  "𝜵": ["nabla", ["BOLD", "ITALIC"]],
  "𝝏": ["pdiff", ["BOLD", "ITALIC"]],
  "𝝯": ["nabla", ["SANS-SERIF", "BOLD"]],
  "𝞉": ["pdiff", ["SANS-SERIF", "BOLD"]],
  "𝞩": ["nabla", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝟃": ["pdiff", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "ˆ": ["^", []],
  "·": ["*", []],
  "·": ["*", []],
  "՚": ["'", []],
  "՜": ["!", []],
  "՝": [",", []],
  "՞": ["?", []],
  "،": [",", []],
  "؍": [",", []],
  "؛": [";", []],
  "؟": ["?", []],
  "٪": ["%", []],
  "٭": ["*", []],
  "܄": [":", []],
  "܅": [":", []],
  "܆": [":", []],
  "܇": [":", []],
  "܈": [":", []],
  "܉": [":", []],
  "߸": [",", []],
  "߹": ["!", []],
  "፣": [",", []],
  "፤": [";", []],
  "፥": [":", []],
  "፦": [":", []],
  "፧": ["?", []],
  "᛫": ["*", []],
  "᛬": [":", []],
  "᛭": ["+", []],
  "᠂": [",", []],
  "᠄": [":", []],
  "᠈": [",", []],
  "᠊": ["-", []],
  "᥄": ["!", []],
  "᥅": ["?", []],
  "᰽": ["*", []],
  "•": ["*", []],
  "‧": ["*", []],
  "′": ["'", []],
  "‵": ["'", []],
  "⁃": ["-", []],
  "⁎": ["*", []],
  "⁏": [";", []],
  "⸱": ["*", []],
  "⸲": [",", []],
  "⸳": ["*", []],
  "⸴": [",", []],
  "⸵": [";", []],
  "꘍": [",", []],
  "꘏": ["?", []],
  "꛴": [":", []],
  "꛵": [",", []],
  "꛶": [";", []],
  "꛷": ["?", []],
  "︑": [",", []],
  "･": ["*", []],
  "𐤟": ["*", []],
};

/** Punteggiatura Unicode → il carattere ASCII equivalente. */
export const punctuation: Record<string, UnicodeReplacement> = {
  "·": ["*", []],
  "·": ["*", []],
  "՚": ["'", []],
  "՜": ["!", []],
  "՝": [",", []],
  "՞": ["?", []],
  "،": [",", []],
  "؍": [",", []],
  "؛": [";", []],
  "؟": ["?", []],
  "٪": ["%", []],
  "٭": ["*", []],
  "܄": [":", []],
  "܅": [":", []],
  "܆": [":", []],
  "܇": [":", []],
  "܈": [":", []],
  "܉": [":", []],
  "߸": [",", []],
  "߹": ["!", []],
  "፣": [",", []],
  "፤": [";", []],
  "፥": [":", []],
  "፦": [":", []],
  "፧": ["?", []],
  "᛫": ["*", []],
  "᛬": [":", []],
  "᛭": ["+", []],
  "᠂": [",", []],
  "᠄": [":", []],
  "᠈": [",", []],
  "᠊": ["-", []],
  "᥄": ["!", []],
  "᥅": ["?", []],
  "᰽": ["*", []],
  "•": ["*", []],
  "‧": ["*", []],
  "′": ["'", []],
  "‵": ["'", []],
  "⁃": ["-", []],
  "⁎": ["*", []],
  "⁏": [";", []],
  "⸱": ["*", []],
  "⸲": [",", []],
  "⸳": ["*", []],
  "⸴": [",", []],
  "⸵": [";", []],
  "꘍": [",", []],
  "꘏": ["?", []],
  "꛴": [":", []],
  "꛵": [",", []],
  "꛶": [";", []],
  "꛷": ["?", []],
  "︑": [",", []],
  "･": ["*", []],
  "𐤟": ["*", []],
};

/** Parentesi Unicode alternative → la parentesi ASCII equivalente. */
export const brackets: Record<string, UnicodeReplacement> = {
  "❨": ["(", []],
  "❪": ["(", []],
  "❴": ["{", []],
  "⟦": ["[", []],
  "⟮": ["(", []],
  "⦃": ["{", []],
  "⦅": ["(", []],
  "⸨": ["(", []],
  "〚": ["[", []],
  "﴿": ["]", []],
  "｟": ["(", []],
  "❩": [")", []],
  "❫": [")", []],
  "❵": ["}", []],
  "⟧": ["]", []],
  "⟯": [")", []],
  "⦄": ["}", []],
  "⦆": [")", []],
  "⸩": [")", []],
  "〛": ["]", []],
  "﴾": ["(", []],
  "｠": [")", []],
};
