/* Derived from Numbas (https://github.com/numbas/Numbas), Copyright 2011-2026 Newcastle University.
 * Licensed under the Apache License, Version 2.0. Ported to TypeScript for SAVINT; see packages/engine/NOTICE. */

// Tabella `letters` di runtime/scripts/unicode-mappings.js (1124 voci, generata
// upstream da https://github.com/numbas/unicode-math-normalization): lettere
// matematiche Unicode (𝐀, 𝔸, 𝕒, ...) verso la lettera ASCII corrispondente e le
// annotazioni di stile. Convertita meccanicamente dal file upstream (una riga
// da 59 KB) mantenendo l'ORDINE delle chiavi, che conta per
// `Parser.normaliseName` (jme.js:1873-1903).
// Fino a quattro voci per riga per restare sotto le 1000 righe di file.

import type { UnicodeReplacement } from "./unicode";

/** Lettere matematiche Unicode → [lettera, annotazioni]. */
export const letters: Record<string, UnicodeReplacement> = {
  "𝐀": ["A", ["BOLD"]], "𝐁": ["B", ["BOLD"]], "𝐂": ["C", ["BOLD"]], "𝐃": ["D", ["BOLD"]],
  "𝐄": ["E", ["BOLD"]], "𝐅": ["F", ["BOLD"]], "𝐆": ["G", ["BOLD"]], "𝐇": ["H", ["BOLD"]],
  "𝐈": ["I", ["BOLD"]], "𝐉": ["J", ["BOLD"]], "𝐊": ["K", ["BOLD"]], "𝐋": ["L", ["BOLD"]],
  "𝐌": ["M", ["BOLD"]], "𝐍": ["N", ["BOLD"]], "𝐎": ["O", ["BOLD"]], "𝐏": ["P", ["BOLD"]],
  "𝐐": ["Q", ["BOLD"]], "𝐑": ["R", ["BOLD"]], "𝐒": ["S", ["BOLD"]], "𝐓": ["T", ["BOLD"]],
  "𝐔": ["U", ["BOLD"]], "𝐕": ["V", ["BOLD"]], "𝐖": ["W", ["BOLD"]], "𝐗": ["X", ["BOLD"]],
  "𝐘": ["Y", ["BOLD"]], "𝐙": ["Z", ["BOLD"]], "𝐚": ["a", ["BOLD"]], "𝐛": ["b", ["BOLD"]],
  "𝐜": ["c", ["BOLD"]], "𝐝": ["d", ["BOLD"]], "𝐞": ["e", ["BOLD"]], "𝐟": ["f", ["BOLD"]],
  "𝐠": ["g", ["BOLD"]], "𝐡": ["h", ["BOLD"]], "𝐢": ["i", ["BOLD"]], "𝐣": ["j", ["BOLD"]],
  "𝐤": ["k", ["BOLD"]], "𝐥": ["l", ["BOLD"]], "𝐦": ["m", ["BOLD"]], "𝐧": ["n", ["BOLD"]],
  "𝐨": ["o", ["BOLD"]], "𝐩": ["p", ["BOLD"]], "𝐪": ["q", ["BOLD"]], "𝐫": ["r", ["BOLD"]],
  "𝐬": ["s", ["BOLD"]], "𝐭": ["t", ["BOLD"]], "𝐮": ["u", ["BOLD"]], "𝐯": ["v", ["BOLD"]],
  "𝐰": ["w", ["BOLD"]], "𝐱": ["x", ["BOLD"]], "𝐲": ["y", ["BOLD"]], "𝐳": ["z", ["BOLD"]],
  "𝐴": ["A", ["ITALIC"]], "𝐵": ["B", ["ITALIC"]], "𝐶": ["C", ["ITALIC"]], "𝐷": ["D", ["ITALIC"]],
  "𝐸": ["E", ["ITALIC"]], "𝐹": ["F", ["ITALIC"]], "𝐺": ["G", ["ITALIC"]], "𝐻": ["H", ["ITALIC"]],
  "𝐼": ["I", ["ITALIC"]], "𝐽": ["J", ["ITALIC"]], "𝐾": ["K", ["ITALIC"]], "𝐿": ["L", ["ITALIC"]],
  "𝑀": ["M", ["ITALIC"]], "𝑁": ["N", ["ITALIC"]], "𝑂": ["O", ["ITALIC"]], "𝑃": ["P", ["ITALIC"]],
  "𝑄": ["Q", ["ITALIC"]], "𝑅": ["R", ["ITALIC"]], "𝑆": ["S", ["ITALIC"]], "𝑇": ["T", ["ITALIC"]],
  "𝑈": ["U", ["ITALIC"]], "𝑉": ["V", ["ITALIC"]], "𝑊": ["W", ["ITALIC"]], "𝑋": ["X", ["ITALIC"]],
  "𝑌": ["Y", ["ITALIC"]], "𝑍": ["Z", ["ITALIC"]], "𝑎": ["a", ["ITALIC"]], "𝑏": ["b", ["ITALIC"]],
  "𝑐": ["c", ["ITALIC"]], "𝑑": ["d", ["ITALIC"]], "𝑒": ["e", ["ITALIC"]], "𝑓": ["f", ["ITALIC"]],
  "𝑔": ["g", ["ITALIC"]], "𝑖": ["i", ["ITALIC"]], "𝑗": ["j", ["ITALIC"]], "𝑘": ["k", ["ITALIC"]],
  "𝑙": ["l", ["ITALIC"]], "𝑚": ["m", ["ITALIC"]], "𝑛": ["n", ["ITALIC"]], "𝑜": ["o", ["ITALIC"]],
  "𝑝": ["p", ["ITALIC"]], "𝑞": ["q", ["ITALIC"]], "𝑟": ["r", ["ITALIC"]], "𝑠": ["s", ["ITALIC"]],
  "𝑡": ["t", ["ITALIC"]], "𝑢": ["u", ["ITALIC"]], "𝑣": ["v", ["ITALIC"]], "𝑤": ["w", ["ITALIC"]],
  "𝑥": ["x", ["ITALIC"]], "𝑦": ["y", ["ITALIC"]], "𝑧": ["z", ["ITALIC"]], "𝑨": ["A", ["BOLD", "ITALIC"]],
  "𝑩": ["B", ["BOLD", "ITALIC"]], "𝑪": ["C", ["BOLD", "ITALIC"]], "𝑫": ["D", ["BOLD", "ITALIC"]], "𝑬": ["E", ["BOLD", "ITALIC"]],
  "𝑭": ["F", ["BOLD", "ITALIC"]], "𝑮": ["G", ["BOLD", "ITALIC"]], "𝑯": ["H", ["BOLD", "ITALIC"]], "𝑰": ["I", ["BOLD", "ITALIC"]],
  "𝑱": ["J", ["BOLD", "ITALIC"]], "𝑲": ["K", ["BOLD", "ITALIC"]], "𝑳": ["L", ["BOLD", "ITALIC"]], "𝑴": ["M", ["BOLD", "ITALIC"]],
  "𝑵": ["N", ["BOLD", "ITALIC"]], "𝑶": ["O", ["BOLD", "ITALIC"]], "𝑷": ["P", ["BOLD", "ITALIC"]], "𝑸": ["Q", ["BOLD", "ITALIC"]],
  "𝑹": ["R", ["BOLD", "ITALIC"]], "𝑺": ["S", ["BOLD", "ITALIC"]], "𝑻": ["T", ["BOLD", "ITALIC"]], "𝑼": ["U", ["BOLD", "ITALIC"]],
  "𝑽": ["V", ["BOLD", "ITALIC"]], "𝑾": ["W", ["BOLD", "ITALIC"]], "𝑿": ["X", ["BOLD", "ITALIC"]], "𝒀": ["Y", ["BOLD", "ITALIC"]],
  "𝒁": ["Z", ["BOLD", "ITALIC"]], "𝒂": ["a", ["BOLD", "ITALIC"]], "𝒃": ["b", ["BOLD", "ITALIC"]], "𝒄": ["c", ["BOLD", "ITALIC"]],
  "𝒅": ["d", ["BOLD", "ITALIC"]], "𝒆": ["e", ["BOLD", "ITALIC"]], "𝒇": ["f", ["BOLD", "ITALIC"]], "𝒈": ["g", ["BOLD", "ITALIC"]],
  "𝒉": ["h", ["BOLD", "ITALIC"]], "𝒊": ["i", ["BOLD", "ITALIC"]], "𝒋": ["j", ["BOLD", "ITALIC"]], "𝒌": ["k", ["BOLD", "ITALIC"]],
  "𝒍": ["l", ["BOLD", "ITALIC"]], "𝒎": ["m", ["BOLD", "ITALIC"]], "𝒏": ["n", ["BOLD", "ITALIC"]], "𝒐": ["o", ["BOLD", "ITALIC"]],
  "𝒑": ["p", ["BOLD", "ITALIC"]], "𝒒": ["q", ["BOLD", "ITALIC"]], "𝒓": ["r", ["BOLD", "ITALIC"]], "𝒔": ["s", ["BOLD", "ITALIC"]],
  "𝒕": ["t", ["BOLD", "ITALIC"]], "𝒖": ["u", ["BOLD", "ITALIC"]], "𝒗": ["v", ["BOLD", "ITALIC"]], "𝒘": ["w", ["BOLD", "ITALIC"]],
  "𝒙": ["x", ["BOLD", "ITALIC"]], "𝒚": ["y", ["BOLD", "ITALIC"]], "𝒛": ["z", ["BOLD", "ITALIC"]], "𝒜": ["A", ["SCRIPT"]],
  "𝒞": ["C", ["SCRIPT"]], "𝒟": ["D", ["SCRIPT"]], "𝒢": ["G", ["SCRIPT"]], "𝒥": ["J", ["SCRIPT"]],
  "𝒦": ["K", ["SCRIPT"]], "𝒩": ["N", ["SCRIPT"]], "𝒪": ["O", ["SCRIPT"]], "𝒫": ["P", ["SCRIPT"]],
  "𝒬": ["Q", ["SCRIPT"]], "𝒮": ["S", ["SCRIPT"]], "𝒯": ["T", ["SCRIPT"]], "𝒰": ["U", ["SCRIPT"]],
  "𝒱": ["V", ["SCRIPT"]], "𝒲": ["W", ["SCRIPT"]], "𝒳": ["X", ["SCRIPT"]], "𝒴": ["Y", ["SCRIPT"]],
  "𝒵": ["Z", ["SCRIPT"]], "𝒶": ["a", ["SCRIPT"]], "𝒷": ["b", ["SCRIPT"]], "𝒸": ["c", ["SCRIPT"]],
  "𝒹": ["d", ["SCRIPT"]], "𝒻": ["f", ["SCRIPT"]], "𝒽": ["h", ["SCRIPT"]], "𝒾": ["i", ["SCRIPT"]],
  "𝒿": ["j", ["SCRIPT"]], "𝓀": ["k", ["SCRIPT"]], "𝓁": ["l", ["SCRIPT"]], "𝓂": ["m", ["SCRIPT"]],
  "𝓃": ["n", ["SCRIPT"]], "𝓅": ["p", ["SCRIPT"]], "𝓆": ["q", ["SCRIPT"]], "𝓇": ["r", ["SCRIPT"]],
  "𝓈": ["s", ["SCRIPT"]], "𝓉": ["t", ["SCRIPT"]], "𝓊": ["u", ["SCRIPT"]], "𝓋": ["v", ["SCRIPT"]],
  "𝓌": ["w", ["SCRIPT"]], "𝓍": ["x", ["SCRIPT"]], "𝓎": ["y", ["SCRIPT"]], "𝓏": ["z", ["SCRIPT"]],
  "𝓐": ["A", ["BOLD", "SCRIPT"]], "𝓑": ["B", ["BOLD", "SCRIPT"]], "𝓒": ["C", ["BOLD", "SCRIPT"]], "𝓓": ["D", ["BOLD", "SCRIPT"]],
  "𝓔": ["E", ["BOLD", "SCRIPT"]], "𝓕": ["F", ["BOLD", "SCRIPT"]], "𝓖": ["G", ["BOLD", "SCRIPT"]], "𝓗": ["H", ["BOLD", "SCRIPT"]],
  "𝓘": ["I", ["BOLD", "SCRIPT"]], "𝓙": ["J", ["BOLD", "SCRIPT"]], "𝓚": ["K", ["BOLD", "SCRIPT"]], "𝓛": ["L", ["BOLD", "SCRIPT"]],
  "𝓜": ["M", ["BOLD", "SCRIPT"]], "𝓝": ["N", ["BOLD", "SCRIPT"]], "𝓞": ["O", ["BOLD", "SCRIPT"]], "𝓟": ["P", ["BOLD", "SCRIPT"]],
  "𝓠": ["Q", ["BOLD", "SCRIPT"]], "𝓡": ["R", ["BOLD", "SCRIPT"]], "𝓢": ["S", ["BOLD", "SCRIPT"]], "𝓣": ["T", ["BOLD", "SCRIPT"]],
  "𝓤": ["U", ["BOLD", "SCRIPT"]], "𝓥": ["V", ["BOLD", "SCRIPT"]], "𝓦": ["W", ["BOLD", "SCRIPT"]], "𝓧": ["X", ["BOLD", "SCRIPT"]],
  "𝓨": ["Y", ["BOLD", "SCRIPT"]], "𝓩": ["Z", ["BOLD", "SCRIPT"]], "𝓪": ["a", ["BOLD", "SCRIPT"]], "𝓫": ["b", ["BOLD", "SCRIPT"]],
  "𝓬": ["c", ["BOLD", "SCRIPT"]], "𝓭": ["d", ["BOLD", "SCRIPT"]], "𝓮": ["e", ["BOLD", "SCRIPT"]], "𝓯": ["f", ["BOLD", "SCRIPT"]],
  "𝓰": ["g", ["BOLD", "SCRIPT"]], "𝓱": ["h", ["BOLD", "SCRIPT"]], "𝓲": ["i", ["BOLD", "SCRIPT"]], "𝓳": ["j", ["BOLD", "SCRIPT"]],
  "𝓴": ["k", ["BOLD", "SCRIPT"]], "𝓵": ["l", ["BOLD", "SCRIPT"]], "𝓶": ["m", ["BOLD", "SCRIPT"]], "𝓷": ["n", ["BOLD", "SCRIPT"]],
  "𝓸": ["o", ["BOLD", "SCRIPT"]], "𝓹": ["p", ["BOLD", "SCRIPT"]], "𝓺": ["q", ["BOLD", "SCRIPT"]], "𝓻": ["r", ["BOLD", "SCRIPT"]],
  "𝓼": ["s", ["BOLD", "SCRIPT"]], "𝓽": ["t", ["BOLD", "SCRIPT"]], "𝓾": ["u", ["BOLD", "SCRIPT"]], "𝓿": ["v", ["BOLD", "SCRIPT"]],
  "𝔀": ["w", ["BOLD", "SCRIPT"]], "𝔁": ["x", ["BOLD", "SCRIPT"]], "𝔂": ["y", ["BOLD", "SCRIPT"]], "𝔃": ["z", ["BOLD", "SCRIPT"]],
  "𝔄": ["A", ["FRAKTUR"]], "𝔅": ["B", ["FRAKTUR"]], "𝔇": ["D", ["FRAKTUR"]], "𝔈": ["E", ["FRAKTUR"]],
  "𝔉": ["F", ["FRAKTUR"]], "𝔊": ["G", ["FRAKTUR"]], "𝔍": ["J", ["FRAKTUR"]], "𝔎": ["K", ["FRAKTUR"]],
  "𝔏": ["L", ["FRAKTUR"]], "𝔐": ["M", ["FRAKTUR"]], "𝔑": ["N", ["FRAKTUR"]], "𝔒": ["O", ["FRAKTUR"]],
  "𝔓": ["P", ["FRAKTUR"]], "𝔔": ["Q", ["FRAKTUR"]], "𝔖": ["S", ["FRAKTUR"]], "𝔗": ["T", ["FRAKTUR"]],
  "𝔘": ["U", ["FRAKTUR"]], "𝔙": ["V", ["FRAKTUR"]], "𝔚": ["W", ["FRAKTUR"]], "𝔛": ["X", ["FRAKTUR"]],
  "𝔜": ["Y", ["FRAKTUR"]], "𝔞": ["a", ["FRAKTUR"]], "𝔟": ["b", ["FRAKTUR"]], "𝔠": ["c", ["FRAKTUR"]],
  "𝔡": ["d", ["FRAKTUR"]], "𝔢": ["e", ["FRAKTUR"]], "𝔣": ["f", ["FRAKTUR"]], "𝔤": ["g", ["FRAKTUR"]],
  "𝔥": ["h", ["FRAKTUR"]], "𝔦": ["i", ["FRAKTUR"]], "𝔧": ["j", ["FRAKTUR"]], "𝔨": ["k", ["FRAKTUR"]],
  "𝔩": ["l", ["FRAKTUR"]], "𝔪": ["m", ["FRAKTUR"]], "𝔫": ["n", ["FRAKTUR"]], "𝔬": ["o", ["FRAKTUR"]],
  "𝔭": ["p", ["FRAKTUR"]], "𝔮": ["q", ["FRAKTUR"]], "𝔯": ["r", ["FRAKTUR"]], "𝔰": ["s", ["FRAKTUR"]],
  "𝔱": ["t", ["FRAKTUR"]], "𝔲": ["u", ["FRAKTUR"]], "𝔳": ["v", ["FRAKTUR"]], "𝔴": ["w", ["FRAKTUR"]],
  "𝔵": ["x", ["FRAKTUR"]], "𝔶": ["y", ["FRAKTUR"]], "𝔷": ["z", ["FRAKTUR"]], "𝔸": ["A", ["DOUBLE-STRUCK"]],
  "𝔹": ["B", ["DOUBLE-STRUCK"]], "𝔻": ["D", ["DOUBLE-STRUCK"]], "𝔼": ["E", ["DOUBLE-STRUCK"]], "𝔽": ["F", ["DOUBLE-STRUCK"]],
  "𝔾": ["G", ["DOUBLE-STRUCK"]], "𝕀": ["I", ["DOUBLE-STRUCK"]], "𝕁": ["J", ["DOUBLE-STRUCK"]], "𝕂": ["K", ["DOUBLE-STRUCK"]],
  "𝕃": ["L", ["DOUBLE-STRUCK"]], "𝕄": ["M", ["DOUBLE-STRUCK"]], "𝕆": ["O", ["DOUBLE-STRUCK"]], "𝕊": ["S", ["DOUBLE-STRUCK"]],
  "𝕋": ["T", ["DOUBLE-STRUCK"]], "𝕌": ["U", ["DOUBLE-STRUCK"]], "𝕍": ["V", ["DOUBLE-STRUCK"]], "𝕎": ["W", ["DOUBLE-STRUCK"]],
  "𝕏": ["X", ["DOUBLE-STRUCK"]], "𝕐": ["Y", ["DOUBLE-STRUCK"]], "𝕒": ["a", ["DOUBLE-STRUCK"]], "𝕓": ["b", ["DOUBLE-STRUCK"]],
  "𝕔": ["c", ["DOUBLE-STRUCK"]], "𝕕": ["d", ["DOUBLE-STRUCK"]], "𝕖": ["e", ["DOUBLE-STRUCK"]], "𝕗": ["f", ["DOUBLE-STRUCK"]],
  "𝕘": ["g", ["DOUBLE-STRUCK"]], "𝕙": ["h", ["DOUBLE-STRUCK"]], "𝕚": ["i", ["DOUBLE-STRUCK"]], "𝕛": ["j", ["DOUBLE-STRUCK"]],
  "𝕜": ["k", ["DOUBLE-STRUCK"]], "𝕝": ["l", ["DOUBLE-STRUCK"]], "𝕞": ["m", ["DOUBLE-STRUCK"]], "𝕟": ["n", ["DOUBLE-STRUCK"]],
  "𝕠": ["o", ["DOUBLE-STRUCK"]], "𝕡": ["p", ["DOUBLE-STRUCK"]], "𝕢": ["q", ["DOUBLE-STRUCK"]], "𝕣": ["r", ["DOUBLE-STRUCK"]],
  "𝕤": ["s", ["DOUBLE-STRUCK"]], "𝕥": ["t", ["DOUBLE-STRUCK"]], "𝕦": ["u", ["DOUBLE-STRUCK"]], "𝕧": ["v", ["DOUBLE-STRUCK"]],
  "𝕨": ["w", ["DOUBLE-STRUCK"]], "𝕩": ["x", ["DOUBLE-STRUCK"]], "𝕪": ["y", ["DOUBLE-STRUCK"]], "𝕫": ["z", ["DOUBLE-STRUCK"]],
  "𝕬": ["A", ["BOLD", "FRAKTUR"]], "𝕭": ["B", ["BOLD", "FRAKTUR"]], "𝕮": ["C", ["BOLD", "FRAKTUR"]], "𝕯": ["D", ["BOLD", "FRAKTUR"]],
  "𝕰": ["E", ["BOLD", "FRAKTUR"]], "𝕱": ["F", ["BOLD", "FRAKTUR"]], "𝕲": ["G", ["BOLD", "FRAKTUR"]], "𝕳": ["H", ["BOLD", "FRAKTUR"]],
  "𝕴": ["I", ["BOLD", "FRAKTUR"]], "𝕵": ["J", ["BOLD", "FRAKTUR"]], "𝕶": ["K", ["BOLD", "FRAKTUR"]], "𝕷": ["L", ["BOLD", "FRAKTUR"]],
  "𝕸": ["M", ["BOLD", "FRAKTUR"]], "𝕹": ["N", ["BOLD", "FRAKTUR"]], "𝕺": ["O", ["BOLD", "FRAKTUR"]], "𝕻": ["P", ["BOLD", "FRAKTUR"]],
  "𝕼": ["Q", ["BOLD", "FRAKTUR"]], "𝕽": ["R", ["BOLD", "FRAKTUR"]], "𝕾": ["S", ["BOLD", "FRAKTUR"]], "𝕿": ["T", ["BOLD", "FRAKTUR"]],
  "𝖀": ["U", ["BOLD", "FRAKTUR"]], "𝖁": ["V", ["BOLD", "FRAKTUR"]], "𝖂": ["W", ["BOLD", "FRAKTUR"]], "𝖃": ["X", ["BOLD", "FRAKTUR"]],
  "𝖄": ["Y", ["BOLD", "FRAKTUR"]], "𝖅": ["Z", ["BOLD", "FRAKTUR"]], "𝖆": ["a", ["BOLD", "FRAKTUR"]], "𝖇": ["b", ["BOLD", "FRAKTUR"]],
  "𝖈": ["c", ["BOLD", "FRAKTUR"]], "𝖉": ["d", ["BOLD", "FRAKTUR"]], "𝖊": ["e", ["BOLD", "FRAKTUR"]], "𝖋": ["f", ["BOLD", "FRAKTUR"]],
  "𝖌": ["g", ["BOLD", "FRAKTUR"]], "𝖍": ["h", ["BOLD", "FRAKTUR"]], "𝖎": ["i", ["BOLD", "FRAKTUR"]], "𝖏": ["j", ["BOLD", "FRAKTUR"]],
  "𝖐": ["k", ["BOLD", "FRAKTUR"]], "𝖑": ["l", ["BOLD", "FRAKTUR"]], "𝖒": ["m", ["BOLD", "FRAKTUR"]], "𝖓": ["n", ["BOLD", "FRAKTUR"]],
  "𝖔": ["o", ["BOLD", "FRAKTUR"]], "𝖕": ["p", ["BOLD", "FRAKTUR"]], "𝖖": ["q", ["BOLD", "FRAKTUR"]], "𝖗": ["r", ["BOLD", "FRAKTUR"]],
  "𝖘": ["s", ["BOLD", "FRAKTUR"]], "𝖙": ["t", ["BOLD", "FRAKTUR"]], "𝖚": ["u", ["BOLD", "FRAKTUR"]], "𝖛": ["v", ["BOLD", "FRAKTUR"]],
  "𝖜": ["w", ["BOLD", "FRAKTUR"]], "𝖝": ["x", ["BOLD", "FRAKTUR"]], "𝖞": ["y", ["BOLD", "FRAKTUR"]], "𝖟": ["z", ["BOLD", "FRAKTUR"]],
  "𝖠": ["A", ["SANS-SERIF"]], "𝖡": ["B", ["SANS-SERIF"]], "𝖢": ["C", ["SANS-SERIF"]], "𝖣": ["D", ["SANS-SERIF"]],
  "𝖤": ["E", ["SANS-SERIF"]], "𝖥": ["F", ["SANS-SERIF"]], "𝖦": ["G", ["SANS-SERIF"]], "𝖧": ["H", ["SANS-SERIF"]],
  "𝖨": ["I", ["SANS-SERIF"]], "𝖩": ["J", ["SANS-SERIF"]], "𝖪": ["K", ["SANS-SERIF"]], "𝖫": ["L", ["SANS-SERIF"]],
  "𝖬": ["M", ["SANS-SERIF"]], "𝖭": ["N", ["SANS-SERIF"]], "𝖮": ["O", ["SANS-SERIF"]], "𝖯": ["P", ["SANS-SERIF"]],
  "𝖰": ["Q", ["SANS-SERIF"]], "𝖱": ["R", ["SANS-SERIF"]], "𝖲": ["S", ["SANS-SERIF"]], "𝖳": ["T", ["SANS-SERIF"]],
  "𝖴": ["U", ["SANS-SERIF"]], "𝖵": ["V", ["SANS-SERIF"]], "𝖶": ["W", ["SANS-SERIF"]], "𝖷": ["X", ["SANS-SERIF"]],
  "𝖸": ["Y", ["SANS-SERIF"]], "𝖹": ["Z", ["SANS-SERIF"]], "𝖺": ["a", ["SANS-SERIF"]], "𝖻": ["b", ["SANS-SERIF"]],
  "𝖼": ["c", ["SANS-SERIF"]], "𝖽": ["d", ["SANS-SERIF"]], "𝖾": ["e", ["SANS-SERIF"]], "𝖿": ["f", ["SANS-SERIF"]],
  "𝗀": ["g", ["SANS-SERIF"]], "𝗁": ["h", ["SANS-SERIF"]], "𝗂": ["i", ["SANS-SERIF"]], "𝗃": ["j", ["SANS-SERIF"]],
  "𝗄": ["k", ["SANS-SERIF"]], "𝗅": ["l", ["SANS-SERIF"]], "𝗆": ["m", ["SANS-SERIF"]], "𝗇": ["n", ["SANS-SERIF"]],
  "𝗈": ["o", ["SANS-SERIF"]], "𝗉": ["p", ["SANS-SERIF"]], "𝗊": ["q", ["SANS-SERIF"]], "𝗋": ["r", ["SANS-SERIF"]],
  "𝗌": ["s", ["SANS-SERIF"]], "𝗍": ["t", ["SANS-SERIF"]], "𝗎": ["u", ["SANS-SERIF"]], "𝗏": ["v", ["SANS-SERIF"]],
  "𝗐": ["w", ["SANS-SERIF"]], "𝗑": ["x", ["SANS-SERIF"]], "𝗒": ["y", ["SANS-SERIF"]], "𝗓": ["z", ["SANS-SERIF"]],
  "𝗔": ["A", ["SANS-SERIF", "BOLD"]], "𝗕": ["B", ["SANS-SERIF", "BOLD"]], "𝗖": ["C", ["SANS-SERIF", "BOLD"]], "𝗗": ["D", ["SANS-SERIF", "BOLD"]],
  "𝗘": ["E", ["SANS-SERIF", "BOLD"]], "𝗙": ["F", ["SANS-SERIF", "BOLD"]], "𝗚": ["G", ["SANS-SERIF", "BOLD"]], "𝗛": ["H", ["SANS-SERIF", "BOLD"]],
  "𝗜": ["I", ["SANS-SERIF", "BOLD"]], "𝗝": ["J", ["SANS-SERIF", "BOLD"]], "𝗞": ["K", ["SANS-SERIF", "BOLD"]], "𝗟": ["L", ["SANS-SERIF", "BOLD"]],
  "𝗠": ["M", ["SANS-SERIF", "BOLD"]], "𝗡": ["N", ["SANS-SERIF", "BOLD"]], "𝗢": ["O", ["SANS-SERIF", "BOLD"]], "𝗣": ["P", ["SANS-SERIF", "BOLD"]],
  "𝗤": ["Q", ["SANS-SERIF", "BOLD"]], "𝗥": ["R", ["SANS-SERIF", "BOLD"]], "𝗦": ["S", ["SANS-SERIF", "BOLD"]], "𝗧": ["T", ["SANS-SERIF", "BOLD"]],
  "𝗨": ["U", ["SANS-SERIF", "BOLD"]], "𝗩": ["V", ["SANS-SERIF", "BOLD"]], "𝗪": ["W", ["SANS-SERIF", "BOLD"]], "𝗫": ["X", ["SANS-SERIF", "BOLD"]],
  "𝗬": ["Y", ["SANS-SERIF", "BOLD"]], "𝗭": ["Z", ["SANS-SERIF", "BOLD"]], "𝗮": ["a", ["SANS-SERIF", "BOLD"]], "𝗯": ["b", ["SANS-SERIF", "BOLD"]],
  "𝗰": ["c", ["SANS-SERIF", "BOLD"]], "𝗱": ["d", ["SANS-SERIF", "BOLD"]], "𝗲": ["e", ["SANS-SERIF", "BOLD"]], "𝗳": ["f", ["SANS-SERIF", "BOLD"]],
  "𝗴": ["g", ["SANS-SERIF", "BOLD"]], "𝗵": ["h", ["SANS-SERIF", "BOLD"]], "𝗶": ["i", ["SANS-SERIF", "BOLD"]], "𝗷": ["j", ["SANS-SERIF", "BOLD"]],
  "𝗸": ["k", ["SANS-SERIF", "BOLD"]], "𝗹": ["l", ["SANS-SERIF", "BOLD"]], "𝗺": ["m", ["SANS-SERIF", "BOLD"]], "𝗻": ["n", ["SANS-SERIF", "BOLD"]],
  "𝗼": ["o", ["SANS-SERIF", "BOLD"]], "𝗽": ["p", ["SANS-SERIF", "BOLD"]], "𝗾": ["q", ["SANS-SERIF", "BOLD"]], "𝗿": ["r", ["SANS-SERIF", "BOLD"]],
  "𝘀": ["s", ["SANS-SERIF", "BOLD"]], "𝘁": ["t", ["SANS-SERIF", "BOLD"]], "𝘂": ["u", ["SANS-SERIF", "BOLD"]], "𝘃": ["v", ["SANS-SERIF", "BOLD"]],
  "𝘄": ["w", ["SANS-SERIF", "BOLD"]], "𝘅": ["x", ["SANS-SERIF", "BOLD"]], "𝘆": ["y", ["SANS-SERIF", "BOLD"]], "𝘇": ["z", ["SANS-SERIF", "BOLD"]],
  "𝘈": ["A", ["SANS-SERIF", "ITALIC"]], "𝘉": ["B", ["SANS-SERIF", "ITALIC"]], "𝘊": ["C", ["SANS-SERIF", "ITALIC"]], "𝘋": ["D", ["SANS-SERIF", "ITALIC"]],
  "𝘌": ["E", ["SANS-SERIF", "ITALIC"]], "𝘍": ["F", ["SANS-SERIF", "ITALIC"]], "𝘎": ["G", ["SANS-SERIF", "ITALIC"]], "𝘏": ["H", ["SANS-SERIF", "ITALIC"]],
  "𝘐": ["I", ["SANS-SERIF", "ITALIC"]], "𝘑": ["J", ["SANS-SERIF", "ITALIC"]], "𝘒": ["K", ["SANS-SERIF", "ITALIC"]], "𝘓": ["L", ["SANS-SERIF", "ITALIC"]],
  "𝘔": ["M", ["SANS-SERIF", "ITALIC"]], "𝘕": ["N", ["SANS-SERIF", "ITALIC"]], "𝘖": ["O", ["SANS-SERIF", "ITALIC"]], "𝘗": ["P", ["SANS-SERIF", "ITALIC"]],
  "𝘘": ["Q", ["SANS-SERIF", "ITALIC"]], "𝘙": ["R", ["SANS-SERIF", "ITALIC"]], "𝘚": ["S", ["SANS-SERIF", "ITALIC"]], "𝘛": ["T", ["SANS-SERIF", "ITALIC"]],
  "𝘜": ["U", ["SANS-SERIF", "ITALIC"]], "𝘝": ["V", ["SANS-SERIF", "ITALIC"]], "𝘞": ["W", ["SANS-SERIF", "ITALIC"]], "𝘟": ["X", ["SANS-SERIF", "ITALIC"]],
  "𝘠": ["Y", ["SANS-SERIF", "ITALIC"]], "𝘡": ["Z", ["SANS-SERIF", "ITALIC"]], "𝘢": ["a", ["SANS-SERIF", "ITALIC"]], "𝘣": ["b", ["SANS-SERIF", "ITALIC"]],
  "𝘤": ["c", ["SANS-SERIF", "ITALIC"]], "𝘥": ["d", ["SANS-SERIF", "ITALIC"]], "𝘦": ["e", ["SANS-SERIF", "ITALIC"]], "𝘧": ["f", ["SANS-SERIF", "ITALIC"]],
  "𝘨": ["g", ["SANS-SERIF", "ITALIC"]], "𝘩": ["h", ["SANS-SERIF", "ITALIC"]], "𝘪": ["i", ["SANS-SERIF", "ITALIC"]], "𝘫": ["j", ["SANS-SERIF", "ITALIC"]],
  "𝘬": ["k", ["SANS-SERIF", "ITALIC"]], "𝘭": ["l", ["SANS-SERIF", "ITALIC"]], "𝘮": ["m", ["SANS-SERIF", "ITALIC"]], "𝘯": ["n", ["SANS-SERIF", "ITALIC"]],
  "𝘰": ["o", ["SANS-SERIF", "ITALIC"]], "𝘱": ["p", ["SANS-SERIF", "ITALIC"]], "𝘲": ["q", ["SANS-SERIF", "ITALIC"]], "𝘳": ["r", ["SANS-SERIF", "ITALIC"]],
  "𝘴": ["s", ["SANS-SERIF", "ITALIC"]], "𝘵": ["t", ["SANS-SERIF", "ITALIC"]], "𝘶": ["u", ["SANS-SERIF", "ITALIC"]], "𝘷": ["v", ["SANS-SERIF", "ITALIC"]],
  "𝘸": ["w", ["SANS-SERIF", "ITALIC"]], "𝘹": ["x", ["SANS-SERIF", "ITALIC"]], "𝘺": ["y", ["SANS-SERIF", "ITALIC"]], "𝘻": ["z", ["SANS-SERIF", "ITALIC"]],
  "𝘼": ["A", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝘽": ["B", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝘾": ["C", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝘿": ["D", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙀": ["E", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙁": ["F", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙂": ["G", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙃": ["H", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙄": ["I", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙅": ["J", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙆": ["K", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙇": ["L", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙈": ["M", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙉": ["N", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙊": ["O", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙋": ["P", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙌": ["Q", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙍": ["R", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙎": ["S", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙏": ["T", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙐": ["U", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙑": ["V", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙒": ["W", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙓": ["X", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙔": ["Y", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙕": ["Z", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙖": ["a", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙗": ["b", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙘": ["c", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙙": ["d", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙚": ["e", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙛": ["f", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙜": ["g", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙝": ["h", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙞": ["i", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙟": ["j", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙠": ["k", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙡": ["l", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙢": ["m", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙣": ["n", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙤": ["o", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙥": ["p", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙦": ["q", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙧": ["r", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙨": ["s", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙩": ["t", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙪": ["u", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙫": ["v", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙬": ["w", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙭": ["x", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙮": ["y", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝙯": ["z", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝙰": ["A", ["MONOSPACE"]], "𝙱": ["B", ["MONOSPACE"]], "𝙲": ["C", ["MONOSPACE"]], "𝙳": ["D", ["MONOSPACE"]],
  "𝙴": ["E", ["MONOSPACE"]], "𝙵": ["F", ["MONOSPACE"]], "𝙶": ["G", ["MONOSPACE"]], "𝙷": ["H", ["MONOSPACE"]],
  "𝙸": ["I", ["MONOSPACE"]], "𝙹": ["J", ["MONOSPACE"]], "𝙺": ["K", ["MONOSPACE"]], "𝙻": ["L", ["MONOSPACE"]],
  "𝙼": ["M", ["MONOSPACE"]], "𝙽": ["N", ["MONOSPACE"]], "𝙾": ["O", ["MONOSPACE"]], "𝙿": ["P", ["MONOSPACE"]],
  "𝚀": ["Q", ["MONOSPACE"]], "𝚁": ["R", ["MONOSPACE"]], "𝚂": ["S", ["MONOSPACE"]], "𝚃": ["T", ["MONOSPACE"]],
  "𝚄": ["U", ["MONOSPACE"]], "𝚅": ["V", ["MONOSPACE"]], "𝚆": ["W", ["MONOSPACE"]], "𝚇": ["X", ["MONOSPACE"]],
  "𝚈": ["Y", ["MONOSPACE"]], "𝚉": ["Z", ["MONOSPACE"]], "𝚊": ["a", ["MONOSPACE"]], "𝚋": ["b", ["MONOSPACE"]],
  "𝚌": ["c", ["MONOSPACE"]], "𝚍": ["d", ["MONOSPACE"]], "𝚎": ["e", ["MONOSPACE"]], "𝚏": ["f", ["MONOSPACE"]],
  "𝚐": ["g", ["MONOSPACE"]], "𝚑": ["h", ["MONOSPACE"]], "𝚒": ["i", ["MONOSPACE"]], "𝚓": ["j", ["MONOSPACE"]],
  "𝚔": ["k", ["MONOSPACE"]], "𝚕": ["l", ["MONOSPACE"]], "𝚖": ["m", ["MONOSPACE"]], "𝚗": ["n", ["MONOSPACE"]],
  "𝚘": ["o", ["MONOSPACE"]], "𝚙": ["p", ["MONOSPACE"]], "𝚚": ["q", ["MONOSPACE"]], "𝚛": ["r", ["MONOSPACE"]],
  "𝚜": ["s", ["MONOSPACE"]], "𝚝": ["t", ["MONOSPACE"]], "𝚞": ["u", ["MONOSPACE"]], "𝚟": ["v", ["MONOSPACE"]],
  "𝚠": ["w", ["MONOSPACE"]], "𝚡": ["x", ["MONOSPACE"]], "𝚢": ["y", ["MONOSPACE"]], "𝚣": ["z", ["MONOSPACE"]],
  "𝚤": ["ı", ["ITALIC"]], "𝚥": ["ȷ", ["ITALIC"]], "𝚨": ["Α", ["BOLD"]], "𝚩": ["Β", ["BOLD"]],
  "𝚪": ["Γ", ["BOLD"]], "𝚫": ["Δ", ["BOLD"]], "𝚬": ["Ε", ["BOLD"]], "𝚭": ["Ζ", ["BOLD"]],
  "𝚮": ["Η", ["BOLD"]], "𝚯": ["Θ", ["BOLD"]], "𝚰": ["Ι", ["BOLD"]], "𝚱": ["Κ", ["BOLD"]],
  "𝚲": ["Λ", ["BOLD"]], "𝚳": ["Μ", ["BOLD"]], "𝚴": ["Ν", ["BOLD"]], "𝚵": ["Ξ", ["BOLD"]],
  "𝚶": ["Ο", ["BOLD"]], "𝚷": ["Π", ["BOLD"]], "𝚸": ["Ρ", ["BOLD"]], "𝚹": ["Θ", ["BOLD"]],
  "𝚺": ["Σ", ["BOLD"]], "𝚻": ["Τ", ["BOLD"]], "𝚼": ["Υ", ["BOLD"]], "𝚽": ["Φ", ["BOLD"]],
  "𝚾": ["Χ", ["BOLD"]], "𝚿": ["Ψ", ["BOLD"]], "𝛀": ["Ω", ["BOLD"]], "𝛂": ["α", ["BOLD"]],
  "𝛃": ["β", ["BOLD"]], "𝛄": ["γ", ["BOLD"]], "𝛅": ["δ", ["BOLD"]], "𝛆": ["ε", ["BOLD"]],
  "𝛇": ["ζ", ["BOLD"]], "𝛈": ["η", ["BOLD"]], "𝛉": ["θ", ["BOLD"]], "𝛊": ["ι", ["BOLD"]],
  "𝛋": ["κ", ["BOLD"]], "𝛌": ["λ", ["BOLD"]], "𝛍": ["μ", ["BOLD"]], "𝛎": ["ν", ["BOLD"]],
  "𝛏": ["ξ", ["BOLD"]], "𝛐": ["ο", ["BOLD"]], "𝛑": ["π", ["BOLD"]], "𝛒": ["ρ", ["BOLD"]],
  "𝛓": ["ς", ["BOLD"]], "𝛔": ["σ", ["BOLD"]], "𝛕": ["τ", ["BOLD"]], "𝛖": ["υ", ["BOLD"]],
  "𝛗": ["φ", ["BOLD"]], "𝛘": ["χ", ["BOLD"]], "𝛙": ["ψ", ["BOLD"]], "𝛚": ["ω", ["BOLD"]],
  "𝛜": ["ε", ["BOLD"]], "𝛝": ["θ", ["BOLD"]], "𝛞": ["κ", ["BOLD"]], "𝛟": ["φ", ["BOLD"]],
  "𝛠": ["ρ", ["BOLD"]], "𝛡": ["π", ["BOLD"]], "𝛢": ["Α", ["ITALIC"]], "𝛣": ["Β", ["ITALIC"]],
  "𝛤": ["Γ", ["ITALIC"]], "𝛥": ["Δ", ["ITALIC"]], "𝛦": ["Ε", ["ITALIC"]], "𝛧": ["Ζ", ["ITALIC"]],
  "𝛨": ["Η", ["ITALIC"]], "𝛩": ["Θ", ["ITALIC"]], "𝛪": ["Ι", ["ITALIC"]], "𝛫": ["Κ", ["ITALIC"]],
  "𝛬": ["Λ", ["ITALIC"]], "𝛭": ["Μ", ["ITALIC"]], "𝛮": ["Ν", ["ITALIC"]], "𝛯": ["Ξ", ["ITALIC"]],
  "𝛰": ["Ο", ["ITALIC"]], "𝛱": ["Π", ["ITALIC"]], "𝛲": ["Ρ", ["ITALIC"]], "𝛳": ["Θ", ["ITALIC"]],
  "𝛴": ["Σ", ["ITALIC"]], "𝛵": ["Τ", ["ITALIC"]], "𝛶": ["Υ", ["ITALIC"]], "𝛷": ["Φ", ["ITALIC"]],
  "𝛸": ["Χ", ["ITALIC"]], "𝛹": ["Ψ", ["ITALIC"]], "𝛺": ["Ω", ["ITALIC"]], "𝛼": ["α", ["ITALIC"]],
  "𝛽": ["β", ["ITALIC"]], "𝛾": ["γ", ["ITALIC"]], "𝛿": ["δ", ["ITALIC"]], "𝜀": ["ε", ["ITALIC"]],
  "𝜁": ["ζ", ["ITALIC"]], "𝜂": ["η", ["ITALIC"]], "𝜃": ["θ", ["ITALIC"]], "𝜄": ["ι", ["ITALIC"]],
  "𝜅": ["κ", ["ITALIC"]], "𝜆": ["λ", ["ITALIC"]], "𝜇": ["μ", ["ITALIC"]], "𝜈": ["ν", ["ITALIC"]],
  "𝜉": ["ξ", ["ITALIC"]], "𝜊": ["ο", ["ITALIC"]], "𝜋": ["π", ["ITALIC"]], "𝜌": ["ρ", ["ITALIC"]],
  "𝜍": ["ς", ["ITALIC"]], "𝜎": ["σ", ["ITALIC"]], "𝜏": ["τ", ["ITALIC"]], "𝜐": ["υ", ["ITALIC"]],
  "𝜑": ["φ", ["ITALIC"]], "𝜒": ["χ", ["ITALIC"]], "𝜓": ["ψ", ["ITALIC"]], "𝜔": ["ω", ["ITALIC"]],
  "𝜖": ["ε", ["ITALIC"]], "𝜗": ["θ", ["ITALIC"]], "𝜘": ["κ", ["ITALIC"]], "𝜙": ["φ", ["ITALIC"]],
  "𝜚": ["ρ", ["ITALIC"]], "𝜛": ["π", ["ITALIC"]], "𝜜": ["Α", ["BOLD", "ITALIC"]], "𝜝": ["Β", ["BOLD", "ITALIC"]],
  "𝜞": ["Γ", ["BOLD", "ITALIC"]], "𝜟": ["Δ", ["BOLD", "ITALIC"]], "𝜠": ["Ε", ["BOLD", "ITALIC"]], "𝜡": ["Ζ", ["BOLD", "ITALIC"]],
  "𝜢": ["Η", ["BOLD", "ITALIC"]], "𝜣": ["Θ", ["BOLD", "ITALIC"]], "𝜤": ["Ι", ["BOLD", "ITALIC"]], "𝜥": ["Κ", ["BOLD", "ITALIC"]],
  "𝜦": ["Λ", ["BOLD", "ITALIC"]], "𝜧": ["Μ", ["BOLD", "ITALIC"]], "𝜨": ["Ν", ["BOLD", "ITALIC"]], "𝜩": ["Ξ", ["BOLD", "ITALIC"]],
  "𝜪": ["Ο", ["BOLD", "ITALIC"]], "𝜫": ["Π", ["BOLD", "ITALIC"]], "𝜬": ["Ρ", ["BOLD", "ITALIC"]], "𝜭": ["Θ", ["BOLD", "ITALIC"]],
  "𝜮": ["Σ", ["BOLD", "ITALIC"]], "𝜯": ["Τ", ["BOLD", "ITALIC"]], "𝜰": ["Υ", ["BOLD", "ITALIC"]], "𝜱": ["Φ", ["BOLD", "ITALIC"]],
  "𝜲": ["Χ", ["BOLD", "ITALIC"]], "𝜳": ["Ψ", ["BOLD", "ITALIC"]], "𝜴": ["Ω", ["BOLD", "ITALIC"]], "𝜶": ["α", ["BOLD", "ITALIC"]],
  "𝜷": ["β", ["BOLD", "ITALIC"]], "𝜸": ["γ", ["BOLD", "ITALIC"]], "𝜹": ["δ", ["BOLD", "ITALIC"]], "𝜺": ["ε", ["BOLD", "ITALIC"]],
  "𝜻": ["ζ", ["BOLD", "ITALIC"]], "𝜼": ["η", ["BOLD", "ITALIC"]], "𝜽": ["θ", ["BOLD", "ITALIC"]], "𝜾": ["ι", ["BOLD", "ITALIC"]],
  "𝜿": ["κ", ["BOLD", "ITALIC"]], "𝝀": ["λ", ["BOLD", "ITALIC"]], "𝝁": ["μ", ["BOLD", "ITALIC"]], "𝝂": ["ν", ["BOLD", "ITALIC"]],
  "𝝃": ["ξ", ["BOLD", "ITALIC"]], "𝝄": ["ο", ["BOLD", "ITALIC"]], "𝝅": ["π", ["BOLD", "ITALIC"]], "𝝆": ["ρ", ["BOLD", "ITALIC"]],
  "𝝇": ["ς", ["BOLD", "ITALIC"]], "𝝈": ["σ", ["BOLD", "ITALIC"]], "𝝉": ["τ", ["BOLD", "ITALIC"]], "𝝊": ["υ", ["BOLD", "ITALIC"]],
  "𝝋": ["φ", ["BOLD", "ITALIC"]], "𝝌": ["χ", ["BOLD", "ITALIC"]], "𝝍": ["ψ", ["BOLD", "ITALIC"]], "𝝎": ["ω", ["BOLD", "ITALIC"]],
  "𝝐": ["ε", ["BOLD", "ITALIC"]], "𝝑": ["θ", ["BOLD", "ITALIC"]], "𝝒": ["κ", ["BOLD", "ITALIC"]], "𝝓": ["φ", ["BOLD", "ITALIC"]],
  "𝝔": ["ρ", ["BOLD", "ITALIC"]], "𝝕": ["π", ["BOLD", "ITALIC"]], "𝝖": ["Α", ["SANS-SERIF", "BOLD"]], "𝝗": ["Β", ["SANS-SERIF", "BOLD"]],
  "𝝘": ["Γ", ["SANS-SERIF", "BOLD"]], "𝝙": ["Δ", ["SANS-SERIF", "BOLD"]], "𝝚": ["Ε", ["SANS-SERIF", "BOLD"]], "𝝛": ["Ζ", ["SANS-SERIF", "BOLD"]],
  "𝝜": ["Η", ["SANS-SERIF", "BOLD"]], "𝝝": ["Θ", ["SANS-SERIF", "BOLD"]], "𝝞": ["Ι", ["SANS-SERIF", "BOLD"]], "𝝟": ["Κ", ["SANS-SERIF", "BOLD"]],
  "𝝠": ["Λ", ["SANS-SERIF", "BOLD"]], "𝝡": ["Μ", ["SANS-SERIF", "BOLD"]], "𝝢": ["Ν", ["SANS-SERIF", "BOLD"]], "𝝣": ["Ξ", ["SANS-SERIF", "BOLD"]],
  "𝝤": ["Ο", ["SANS-SERIF", "BOLD"]], "𝝥": ["Π", ["SANS-SERIF", "BOLD"]], "𝝦": ["Ρ", ["SANS-SERIF", "BOLD"]], "𝝧": ["Θ", ["SANS-SERIF", "BOLD"]],
  "𝝨": ["Σ", ["SANS-SERIF", "BOLD"]], "𝝩": ["Τ", ["SANS-SERIF", "BOLD"]], "𝝪": ["Υ", ["SANS-SERIF", "BOLD"]], "𝝫": ["Φ", ["SANS-SERIF", "BOLD"]],
  "𝝬": ["Χ", ["SANS-SERIF", "BOLD"]], "𝝭": ["Ψ", ["SANS-SERIF", "BOLD"]], "𝝮": ["Ω", ["SANS-SERIF", "BOLD"]], "𝝰": ["α", ["SANS-SERIF", "BOLD"]],
  "𝝱": ["β", ["SANS-SERIF", "BOLD"]], "𝝲": ["γ", ["SANS-SERIF", "BOLD"]], "𝝳": ["δ", ["SANS-SERIF", "BOLD"]], "𝝴": ["ε", ["SANS-SERIF", "BOLD"]],
  "𝝵": ["ζ", ["SANS-SERIF", "BOLD"]], "𝝶": ["η", ["SANS-SERIF", "BOLD"]], "𝝷": ["θ", ["SANS-SERIF", "BOLD"]], "𝝸": ["ι", ["SANS-SERIF", "BOLD"]],
  "𝝹": ["κ", ["SANS-SERIF", "BOLD"]], "𝝺": ["λ", ["SANS-SERIF", "BOLD"]], "𝝻": ["μ", ["SANS-SERIF", "BOLD"]], "𝝼": ["ν", ["SANS-SERIF", "BOLD"]],
  "𝝽": ["ξ", ["SANS-SERIF", "BOLD"]], "𝝾": ["ο", ["SANS-SERIF", "BOLD"]], "𝝿": ["π", ["SANS-SERIF", "BOLD"]], "𝞀": ["ρ", ["SANS-SERIF", "BOLD"]],
  "𝞁": ["ς", ["SANS-SERIF", "BOLD"]], "𝞂": ["σ", ["SANS-SERIF", "BOLD"]], "𝞃": ["τ", ["SANS-SERIF", "BOLD"]], "𝞄": ["υ", ["SANS-SERIF", "BOLD"]],
  "𝞅": ["φ", ["SANS-SERIF", "BOLD"]], "𝞆": ["χ", ["SANS-SERIF", "BOLD"]], "𝞇": ["ψ", ["SANS-SERIF", "BOLD"]], "𝞈": ["ω", ["SANS-SERIF", "BOLD"]],
  "𝞊": ["ε", ["SANS-SERIF", "BOLD"]], "𝞋": ["θ", ["SANS-SERIF", "BOLD"]], "𝞌": ["κ", ["SANS-SERIF", "BOLD"]], "𝞍": ["φ", ["SANS-SERIF", "BOLD"]],
  "𝞎": ["ρ", ["SANS-SERIF", "BOLD"]], "𝞏": ["π", ["SANS-SERIF", "BOLD"]], "𝞐": ["Α", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞑": ["Β", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞒": ["Γ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞓": ["Δ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞔": ["Ε", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞕": ["Ζ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞖": ["Η", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞗": ["Θ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞘": ["Ι", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞙": ["Κ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞚": ["Λ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞛": ["Μ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞜": ["Ν", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞝": ["Ξ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞞": ["Ο", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞟": ["Π", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞠": ["Ρ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞡": ["Θ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞢": ["Σ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞣": ["Τ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞤": ["Υ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞥": ["Φ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞦": ["Χ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞧": ["Ψ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞨": ["Ω", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞪": ["α", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞫": ["β", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞬": ["γ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞭": ["δ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞮": ["ε", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞯": ["ζ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞰": ["η", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞱": ["θ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞲": ["ι", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞳": ["κ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞴": ["λ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞵": ["μ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞶": ["ν", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞷": ["ξ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞸": ["ο", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞹": ["π", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞺": ["ρ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞻": ["ς", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞼": ["σ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞽": ["τ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝞾": ["υ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝞿": ["φ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟀": ["χ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟁": ["ψ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟂": ["ω", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝟄": ["ε", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟅": ["θ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟆": ["κ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟇": ["φ", ["SANS-SERIF", "BOLD", "ITALIC"]],
  "𝟈": ["ρ", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟉": ["π", ["SANS-SERIF", "BOLD", "ITALIC"]], "𝟊": ["Ϝ", ["BOLD"]], "𝟋": ["ϝ", ["BOLD"]],
  "𞸀": ["ا", []], "𞸁": ["ب", []], "𞸂": ["ج", []], "𞸃": ["د", []],
  "𞸅": ["و", []], "𞸆": ["ز", []], "𞸇": ["ح", []], "𞸈": ["ط", []],
  "𞸉": ["ي", []], "𞸊": ["ك", []], "𞸋": ["ل", []], "𞸌": ["م", []],
  "𞸍": ["ن", []], "𞸎": ["س", []], "𞸏": ["ع", []], "𞸐": ["ف", []],
  "𞸑": ["ص", []], "𞸒": ["ق", []], "𞸓": ["ر", []], "𞸔": ["ش", []],
  "𞸕": ["ت", []], "𞸖": ["ث", []], "𞸗": ["خ", []], "𞸘": ["ذ", []],
  "𞸙": ["ض", []], "𞸚": ["ظ", []], "𞸛": ["غ", []], "𞸜": ["ٮ", ["DOTLESS"]],
  "𞸝": ["ں", ["DOTLESS"]], "𞸞": ["ڡ", ["DOTLESS"]], "𞸟": ["ٯ", ["DOTLESS"]], "𞸡": ["ب", ["INITIAL"]],
  "𞸢": ["ج", ["INITIAL"]], "𞸤": ["ه", ["INITIAL"]], "𞸧": ["ح", ["INITIAL"]], "𞸩": ["ي", ["INITIAL"]],
  "𞸪": ["ك", ["INITIAL"]], "𞸫": ["ل", ["INITIAL"]], "𞸬": ["م", ["INITIAL"]], "𞸭": ["ن", ["INITIAL"]],
  "𞸮": ["س", ["INITIAL"]], "𞸯": ["ع", ["INITIAL"]], "𞸰": ["ف", ["INITIAL"]], "𞸱": ["ص", ["INITIAL"]],
  "𞸲": ["ق", ["INITIAL"]], "𞸴": ["ش", ["INITIAL"]], "𞸵": ["ت", ["INITIAL"]], "𞸶": ["ث", ["INITIAL"]],
  "𞸷": ["خ", ["INITIAL"]], "𞸹": ["ض", ["INITIAL"]], "𞸻": ["غ", ["INITIAL"]], "𞹂": ["ج", ["TAILED"]],
  "𞹇": ["ح", ["TAILED"]], "𞹉": ["ي", ["TAILED"]], "𞹋": ["ل", ["TAILED"]], "𞹍": ["ن", ["TAILED"]],
  "𞹎": ["س", ["TAILED"]], "𞹏": ["ع", ["TAILED"]], "𞹑": ["ص", ["TAILED"]], "𞹒": ["ق", ["TAILED"]],
  "𞹔": ["ش", ["TAILED"]], "𞹗": ["خ", ["TAILED"]], "𞹙": ["ض", ["TAILED"]], "𞹛": ["غ", ["TAILED"]],
  "𞹝": ["ں", ["TAILED", "DOTLESS"]], "𞹟": ["ٯ", ["TAILED", "DOTLESS"]], "𞹡": ["ب", ["STRETCHED"]], "𞹢": ["ج", ["STRETCHED"]],
  "𞹤": ["ه", ["STRETCHED"]], "𞹧": ["ح", ["STRETCHED"]], "𞹨": ["ط", ["STRETCHED"]], "𞹩": ["ي", ["STRETCHED"]],
  "𞹪": ["ك", ["STRETCHED"]], "𞹬": ["م", ["STRETCHED"]], "𞹭": ["ن", ["STRETCHED"]], "𞹮": ["س", ["STRETCHED"]],
  "𞹯": ["ع", ["STRETCHED"]], "𞹰": ["ف", ["STRETCHED"]], "𞹱": ["ص", ["STRETCHED"]], "𞹲": ["ق", ["STRETCHED"]],
  "𞹴": ["ش", ["STRETCHED"]], "𞹵": ["ت", ["STRETCHED"]], "𞹶": ["ث", ["STRETCHED"]], "𞹷": ["خ", ["STRETCHED"]],
  "𞹹": ["ض", ["STRETCHED"]], "𞹺": ["ظ", ["STRETCHED"]], "𞹻": ["غ", ["STRETCHED"]], "𞹼": ["ٮ", ["STRETCHED", "DOTLESS"]],
  "𞹾": ["ڡ", ["STRETCHED", "DOTLESS"]], "𞺀": ["ا", ["LOOPED"]], "𞺁": ["ب", ["LOOPED"]], "𞺂": ["ج", ["LOOPED"]],
  "𞺃": ["د", ["LOOPED"]], "𞺄": ["ه", ["LOOPED"]], "𞺅": ["و", ["LOOPED"]], "𞺆": ["ز", ["LOOPED"]],
  "𞺇": ["ح", ["LOOPED"]], "𞺈": ["ط", ["LOOPED"]], "𞺉": ["ي", ["LOOPED"]], "𞺋": ["ل", ["LOOPED"]],
  "𞺌": ["م", ["LOOPED"]], "𞺍": ["ن", ["LOOPED"]], "𞺎": ["س", ["LOOPED"]], "𞺏": ["ع", ["LOOPED"]],
  "𞺐": ["ف", ["LOOPED"]], "𞺑": ["ص", ["LOOPED"]], "𞺒": ["ق", ["LOOPED"]], "𞺓": ["ر", ["LOOPED"]],
  "𞺔": ["ش", ["LOOPED"]], "𞺕": ["ت", ["LOOPED"]], "𞺖": ["ث", ["LOOPED"]], "𞺗": ["خ", ["LOOPED"]],
  "𞺘": ["ذ", ["LOOPED"]], "𞺙": ["ض", ["LOOPED"]], "𞺚": ["ظ", ["LOOPED"]], "𞺛": ["غ", ["LOOPED"]],
  "𞺡": ["ب", ["DOUBLE-STRUCK"]], "𞺢": ["ج", ["DOUBLE-STRUCK"]], "𞺣": ["د", ["DOUBLE-STRUCK"]], "𞺥": ["و", ["DOUBLE-STRUCK"]],
  "𞺦": ["ز", ["DOUBLE-STRUCK"]], "𞺧": ["ح", ["DOUBLE-STRUCK"]], "𞺨": ["ط", ["DOUBLE-STRUCK"]], "𞺩": ["ي", ["DOUBLE-STRUCK"]],
  "𞺫": ["ل", ["DOUBLE-STRUCK"]], "𞺬": ["م", ["DOUBLE-STRUCK"]], "𞺭": ["ن", ["DOUBLE-STRUCK"]], "𞺮": ["س", ["DOUBLE-STRUCK"]],
  "𞺯": ["ع", ["DOUBLE-STRUCK"]], "𞺰": ["ف", ["DOUBLE-STRUCK"]], "𞺱": ["ص", ["DOUBLE-STRUCK"]], "𞺲": ["ق", ["DOUBLE-STRUCK"]],
  "𞺳": ["ر", ["DOUBLE-STRUCK"]], "𞺴": ["ش", ["DOUBLE-STRUCK"]], "𞺵": ["ت", ["DOUBLE-STRUCK"]], "𞺶": ["ث", ["DOUBLE-STRUCK"]],
  "𞺷": ["خ", ["DOUBLE-STRUCK"]], "𞺸": ["ذ", ["DOUBLE-STRUCK"]], "𞺹": ["ض", ["DOUBLE-STRUCK"]], "𞺺": ["ظ", ["DOUBLE-STRUCK"]],
  "𞺻": ["غ", ["DOUBLE-STRUCK"]], "µ": ["μ", []], "ℇ": ["E", []], "ℎ": ["h", []],
  "ℏ": ["hbar", []], "Ω": ["omega", []], "℧": ["ohm", []], "Å": ["A", ["RING"]],
  "ℂ": ["C", ["DOUBLE-STRUCK"]], "ℍ": ["H", ["DOUBLE-STRUCK"]], "ℕ": ["N", ["DOUBLE-STRUCK"]], "ℙ": ["P", ["DOUBLE-STRUCK"]],
  "ℚ": ["Q", ["DOUBLE-STRUCK"]], "ℝ": ["R", ["DOUBLE-STRUCK"]], "ℤ": ["Z", ["DOUBLE-STRUCK"]], "ℼ": ["pi", ["DOUBLE-STRUCK"]],
  "ℽ": ["gamma", ["DOUBLE-STRUCK"]], "ℾ": ["gamma", ["DOUBLE-STRUCK"]], "ℿ": ["Pi", []], "ⅅ": ["D", ["DOUBLE-STRUCK", "ITALIC"]],
  "ⅆ": ["d", ["DOUBLE-STRUCK", "ITALIC"]], "ⅇ": ["e", ["DOUBLE-STRUCK", "ITALIC"]], "ⅈ": ["i", ["DOUBLE-STRUCK", "ITALIC"]], "ⅉ": ["j", ["DOUBLE-STRUCK", "ITALIC"]],
  "ℊ": ["g", ["SCRIPT"]], "ℋ": ["H", ["SCRIPT"]], "ℐ": ["I", ["SCRIPT"]], "ℒ": ["L", ["SCRIPT"]],
  "ℓ": ["l", ["SCRIPT"]], "ℛ": ["R", ["SCRIPT"]], "ℬ": ["B", ["SCRIPT"]], "ℯ": ["e", ["SCRIPT"]],
  "ℰ": ["E", ["SCRIPT"]], "ℱ": ["F", ["SCRIPT"]], "ℳ": ["M", ["SCRIPT"]], "ℴ": ["o", ["SCRIPT"]],
  "ℌ": ["H", ["BLACK-LETTER"]], "ℑ": ["I", ["BLACK-LETTER"]], "ℜ": ["R", ["BLACK-LETTER"]], "ℨ": ["Z", ["BLACK-LETTER"]],
  "ℭ": ["C", ["BLACK-LETTER"]], "ℵ": ["alef", []], "ℶ": ["bet", []], "ℷ": ["gimel", []],
  "ℸ": ["dalet", []], "∞": ["infinity", []], "∅": ["emptyset", []], "⦰": ["emptyset", []],
};
